version: '3'
services:
  database:
    restart: unless-stopped
    build:
      context: ./Dockerfiles/database
      dockerfile: Dockerfile.dev
    ports:
      - 27017:27017
    env_file:
      - ./Dockerfiles/database/env/development.env
    networks:
      - tour-trigger
  server:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    ports:
      - 3000:3000
    env_file:
      - ./env/development.env
    networks:
      - tour-trigger

networks:
  tour-trigger:
